### ISSUE TITLE
Difference between mean-n-mide and n-mide?

### ISSUE THREAD

**Issue by marshimarocj** [usnistgov/ActEV_Scorer#2]
We are from CMU team and we've successfully run the evaluation software offline. 
In the evaluation plan pdf, there's detailed explanation of n-mide metrics. 
But in the aggregated output of the software, we get mean-n-mide and n-mide. 
What's the difference between these two metrics?
Thank you very much!

**Comment by dmjoy** [comment]
The N_MIDE metric is computed over the aligned (mapped) instances for each activity (this is the "n-mide" measure in the "scores_by_activity.csv" out file), and without regard to a specific activity (this is the "n-mide" measure in the "scores_aggregated.csv" out file).  The "mean-n-mide" in "scores_aggregated.csv" is the mean of "n-mide" scores over all activities (taken from "scores_by_activity.csv").

In general, metrics with the "mean-" prefix are simple averages of the metrics they prefix looking one step down in terms of granularity.  I.e. "mean-" measures in "scores_aggregated.csv" are over the values in "scores_by_activity.csv", and "mean-" measures in "scores_by_activity.csv" are over the values in "pair_metrics".

I hope that helps, let me know if it's still unclear.
