### ISSUE TITLE
Question about "mean-n-mide_num_rejected"

### ISSUE THREAD

**Issue by steveschwarcz** [usnistgov/ActEV_Scorer#4]
Hello,

I wanted to ask about the metric "n-mide_num_rejected."

I was wondering what this correlates to? 

In addition, we ran a test where we fed ground truth data into the system, assigning a confidence of 1.0 to each activity. We observed that this gave us a "mean-n-mide_num_rejected" of 0.08333 and a "n-mide_num_rejected" of 1. Is this intended behaviour?

The ground truth file we used is attached. We can confirm that, except for the addition of the requisite "alertFrame" and "presenceConf" fields, it's identical to the ground truth.

Ground Truth "Output" file: [output_gt.json.zip](https://github.com/usnistgov/ActEV_Scorer/files/1965030/output_gt.json.zip)

Ground Truth: [gt.json.zip](https://github.com/usnistgov/ActEV_Scorer/files/1965040/gt.json.zip)

Thanks,
Steve Schwarcz

**Comment by dmjoy** [comment]
Hi Steve,

This "n-mide_num_rejected" metric is a simple count of the number of mapped activity detections that are being omitted from the N-MIDE calculation for one of two reasons:
- The duration of the reference activity instance is zero (this can happen if the no-score collar is large enough to zero out the reference activity instance)
- If the duration of the possible false alarm space is zero (the reference activity instance spans the entire duration of the video).  This is actually the case here for activity \#733

The "mean-n-mide_num_rejected" is just the mean of "n-mide_num_rejected" metric values from the "scores_by_activity.csv" output file.  In this case for one of the twelve activities, we have an "n-mide_num_rejected" of 1, and 0 for all other activities, giving us a value of 0.083333.

Best,
David
