### ISSUE TITLE
Can not create TFA_activity.dm files

### ISSUE THREAD

**Issue by nishat612** [usnistgov/ActEV_Scorer#42]
when I tried running the example_run.sh it generates this error messages.
[Errno 2] No such file or directory: 'example_run-output/dm/TFA_Closing.dm'
example_run-output/dm/TFA_Closing.dmDNE
[Errno 2] No such file or directory: 'example_run-output/dm/TFA_Closing_Trunk.dm'
example_run-output/dm/TFA_Closing_Trunk.dmDNE
[Errno 2] No such file or directory: 'example_run-output/dm/TFA_Entering.dm'

I am running it on windows.

**Comment by jfiscus** [comment]
The tool was written for UNIX-style operating systems.  Are you able to install cygwin on your windows system?

**Comment by Chocorean** [comment]
See https://stackoverflow.com/questions/17619079/python-why-does-os-makedirs-cause-windowserror it might help
